### ISSUE TITLE
Artifacts missing

### ISSUE THREAD

**Issue by Karaulov** [evandrocoan/AmxxEditor#14]
https://ci.appveyor.com/project/evandrocoan/AmxxEditor/branch/master

how to download installer ???/

**Comment by evandrocoan** [comment]
https://github.com/evandrocoan/AmxxEditor#by-package-control

**Comment by Karaulov** [comment]
@evandrocoan not works!!!
![3ALFDp3 1](https://user-images.githubusercontent.com/6445336/66196446-354ef180-e6a1-11e9-974d-d874472f76fb.png)
I can't enter this command from https://github.com/evandrocoan/AmxxEditor#by-package-control

**Comment by Karaulov** [comment]
I can't do it: 
![JgitKIq 1](https://user-images.githubusercontent.com/6445336/66196503-54e61a00-e6a1-11e9-8231-f7e0555caa33.png)

**Comment by evandrocoan** [comment]
You need to add it there, then, your screenshot should look like this:
![image](https://user-images.githubusercontent.com/5332158/66241628-e2dbf800-e6d5-11e9-8beb-649297addad1.png)

Once you do that, just save the file and follow the remaining instructions.
