### ISSUE TITLE
Some natives parsed incorrectly

### ISSUE THREAD

**Issue by voed** [evandrocoan/AmxxEditor#15]
Natives that returns array is not parsing and have no autocomplete.
For example:
[fmt](http://www.amxmodx.org/api/string/%5BMAX_FMT_LENGTH%5Dfmt)
or reapi's [rg_firebullets3](https://github.com/s1lentq/reapi/blob/master/reapi/extra/amxmodx/scripting/include/reapi_gamedll.inc#L341)

**Comment by evandrocoan** [comment]
I just fixed and released an update: 

![image](https://user-images.githubusercontent.com/5332158/81989306-674f0b80-9613-11ea-94e6-37feaf49cfcc.png)

**Comment by voed** [comment]
Thanks for quick response, i will try tomorrow
