### ISSUE TITLE
Intellitip for function parameters

### ISSUE THREAD

**Issue by voed** [evandrocoan/AmxxEditor#16]
Is that possible to add intellitip for parameters? Like in VSCode extension:
![image](https://user-images.githubusercontent.com/10352360/82048031-88b80200-96bc-11ea-826a-99611a8cfd00.png)

**Comment by evandrocoan** [comment]
I added a new setting called `enable_inteltip_calls` which enables tooltips when you are inside a function call:
![image](https://user-images.githubusercontent.com/5332158/82104315-cd5b9180-96ec-11ea-8c47-56a6e07dbeae.png)
