### ISSUE TITLE
PythonDebugTools dependency

### ISSUE THREAD

**Issue by janosharsanyi** [evandrocoan/AmxxEditor#2]
```
Package Control: The dependency 'PythonDebugTools' is not currently installed; installing...
Package Control: The dependency 'PythonDebugTools' is not available
Package Control: The dependency 'PythonDebugTools' could not be installed or updated

```

**Comment by evandrocoan** [comment]
Sorry, I forgot about this. The dependency was introduced and I got it was not in package control yet. You can fix this now by adding my channel after the package control default channel.

1. Go to the menu `Preferences -> Package Control`
1. Type `Add Channel` on the opened quick panel and press enter
1. Then enter the following address and press enter:
   ```
   https://raw.githubusercontent.com/evandrocoan/SublimeStudioChannel/master/channel.json
   ```

I already requested it to be pushed to the package control channel on

1. https://github.com/wbond/package_control_channel/pull/6818 Added the PythonDebugTools on repository/dependencies.json

**Comment by evandrocoan** [comment]
The dependency has already been integrated on Package Control, fixing this issue:

1. https://github.com/wbond/package_control_channel/pull/6818 Added the PythonDebugTools on repository/dependencies.json
