### ISSUE TITLE
Bug IntelTip PopUp

### ISSUE THREAD

**Issue by PredatorFly** [evandrocoan/AmxxEditor#20]
Selecting the native opens the popup, but does not close when you click outside it!
![Screenshot_1](https://user-images.githubusercontent.com/33920804/84102780-5fe70c00-a9df-11ea-91bd-effc0bef7879.jpg)

**Comment by evandrocoan** [comment]
Thanks for reporting!

You should get the fix on the next time package updates (in one hour or so)

If you would not like to wait, you can force an immediate update by:

1. Going to the menu `Preferences -> Browse Packages...`
1. Deleting the directory `User/PackagesManager.cache`
1. Deleting the file `User/PackagesManager.last-run`
1. And restarting Sublime Text
1. Now check the Sublime Text console `View -> Show Console`

A few seconds after Sublime Text finish loading, you should be able to see PackagesManager updating the packages.
