### ISSUE TITLE
Make IntelTip overlay rather than break lines

### ISSUE THREAD

**Issue by SmiteIsTrashBro** [evandrocoan/AmxxEditor#22]
Is it possible to have the IntelTip "float" over lines rather than wrap them? The reason for this is that it does make things harder to work with when there are multiple lines. You can see this same functionality in Intellitip plugin for sublime text by jbrooksuk https://github.com/jbrooksuk/Intellitip.

![image](https://user-images.githubusercontent.com/28743155/147250939-668053e9-a88c-49c2-92e5-72b8314fad00.png)

This is what we currently have

![image](https://user-images.githubusercontent.com/28743155/147251228-8bb96637-4e3b-48c4-a8bc-d7807d23d7be.png)

**Comment by evandrocoan** [comment]
It should have a setting for this I think: https://forums.alliedmods.net/showthread.php?p=2704399#post2704399

**Comment by SmiteIsTrashBro** [comment]
I didn't mean to show the popup when you hover with the mouse, what I actually meant is that when you show the popup, it doesn't stay over lines, instead, it will create a gap between the one you're currently viewing and all the others that are below.

**Bad** ❌

![print2](https://user-images.githubusercontent.com/28743155/147386732-3a87ab81-3995-4724-9744-4f03c40d0bf0.png)

**Good** ✔️

![print1](https://user-images.githubusercontent.com/28743155/147386733-86ee1b5c-5c6d-434f-aeb6-7a44848addbe.png)

**Comment by SmiteIsTrashBro** [comment]
Actually, it worked after disabling enable_inteltip_calls and enabling enable_inteltip_name, as in post #197 in the link you sent. I've missed that sorry.
